
# Install rules
install( FILES ${FILES_TO_DEPLOY} DESTINATION include/${PROJECT_NAME} )
install( FILES ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}/config.h 
  DESTINATION include/${PROJECT_NAME} )
install( DIRECTORY ${DIRS_TO_DEPLOY} DESTINATION include/${PROJECT_NAME} )
install(TARGETS ${PROJECT_NAME} 
  EXPORT ${PROJECT_NAME}Targets
  DESTINATION ${INSTALL_LIB_DIR}
  COMPONENT dev)
